apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-green
  template:
    metadata:
      labels:
        app: frontend-green
    spec:
      containers:
        - name: frontend-green
          image: frontend-green:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://backend:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-green
spec:
  type: NodePort
  selector:
    app: frontend-green
  ports:
    - port: 3000
      targetPort: 3200   # FIXED
      nodePort: 30052
